In [ ]:
'Theoretical Questions:'

Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans. NumPy (Numerical Python) is a powerful library in Python used for numerical computing and data analysis. Its primary purpose is to provide support for large, multi-dimensional arrays and matrices, along with a vast collection of high-level mathematical functions to operate on these arrays. Here’s how NumPy enhances Python's capabilities and its advantages in scientific computing and data analysis:

Purpose of NumPy:
Efficient Handling of Arrays and Matrices: NumPy provides a powerful data structure called ndarray (N-dimensional array) that allows efficient storage and manipulation of large datasets. This is essential for handling arrays, matrices, and multi-dimensional data, which are common in data analysis and scientific computing.

Mathematical and Statistical Functions: NumPy comes with a large library of functions for performing mathematical operations, such as linear algebra, Fourier transformations, and statistical operations, making it a core tool in scientific computing.

Interoperability with Other Libraries: Many Python libraries for data science (like pandas, scikit-learn, and TensorFlow) are built on top of NumPy or are highly compatible with it. This makes it a key component in Python’s data analysis ecosystem.

Advantages of NumPy:

Speed and Performance:
NumPy arrays are more efficient and faster than Python lists because they are implemented in C and optimized for performance. This leads to significant speedups in numerical calculations, which are critical in data-heavy applications.
Vectorized operations allow for element-wise computation on arrays, avoiding the need for loops and further speeding up code execution.

Memory Efficiency:
NumPy arrays consume less memory than Python lists because they store data in contiguous memory blocks, and they store elements of the same data type, reducing the memory overhead associated with Python’s flexible object model.
Broadcasting:

NumPy supports broadcasting, a powerful feature that allows arrays of different shapes to be combined in operations without explicitly reshaping them. This enables cleaner and more intuitive code for matrix manipulations.
Mathematical Flexibility:

With its built-in functions for linear algebra (e.g., matrix multiplication, inversion, eigenvalues), statistical analysis (e.g., mean, standard deviation), and random number generation, NumPy simplifies complex scientific and mathematical computations.
Data Handling Capabilities:

NumPy facilitates easy data manipulation such as reshaping, slicing, and indexing of arrays. This is highly beneficial when working with large datasets, especially in machine learning, image processing, and simulations.
Cross-Language Compatibility:

NumPy arrays can be easily integrated with C, C++, and Fortran, making it possible to offload performance-critical parts of the code to these languages for even greater speed improvements.

How NumPy Enhances Python’s Capabilities:

Numerical Precision: While Python has basic capabilities for numbers, NumPy provides more precise tools for floating-point arithmetic and large-scale matrix operations, which are crucial in scientific computing.

Parallelization and Efficiency: NumPy can leverage multi-core CPUs and vectorized operations, providing faster execution of mathematical operations compared to pure Python.

Data Structures for Scientific Work: Python’s native data structures (like lists or dictionaries) are not designed for numerical computation, whereas NumPy’s ndarray is optimized for numerical tasks and scientific data.

In summary, NumPy is essential in scientific computing and data analysis because it boosts Python's capabilities with efficient numerical operations, speed, memory management, and ease of integration with other libraries and languages. This makes it a go-to tool for professionals in data science, engineering, and other technical fields.


Q2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans. np.mean() and np.average() in NumPy are both used to calculate the average value of an array. However, they have subtle differences in their behavior, especially when dealing with weights.

np.mean() calculates the arithmetic mean, which is the sum of all elements divided by the number of elements. This function assumes that all elements contribute equally to the average.

np.average() is more flexible and allows you to specify weights for each element. If you provide a weights array, the function calculates a weighted average, where each element's contribution to the average is proportional to its weight.

When to use np.mean():

- When you want to calculate the simple arithmetic mean of an array and all elements contribute equally.
- When you don't need to assign different weights to elements.

    When to use np.average():

- When you want to calculate a weighted average where different elements have different levels of importance.
- For example, in statistics, you might use weighted averages to account for different sample sizes or variances.

In [2]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])

# Simple arithmetic mean
arithmetic_mean = np.mean(data)
print("Arithmetic mean:", arithmetic_mean)

# Weighted average
weighted_average = np.average(data, weights=weights)
print("Weighted average:", weighted_average)

Arithmetic mean: 3.0
Weighted average: 3.6666666666666665


In summary, np.mean() is appropriate for simple arithmetic averages, while np.average() is more versatile for calculating weighted averages when you need to account for different element contributions.

Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans. Reversing a NumPy array involves changing the order of its elements along a specific axis. NumPy provides the flip() function to accomplish this.

Reversing a 1D array:
To reverse a 1D array, simply pass it to the flip() function. This will reverse the order of elements from the beginning to the end.

In [3]:
import numpy as np

array1d = np.array([1, 2, 3, 4, 5])
reversed_array1d = np.flip(array1d)

print(reversed_array1d)  # Output: [5 4 3 2 1]

[5 4 3 2 1]


Reversing a 2D array:
For 2D arrays, you can specify the axis along which you want to reverse the elements. Using axis=0 will reverse the rows, and axis=1 will reverse the columns.

In [4]:
array2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reversing rows
reversed_rows = np.flip(array2d, axis=0)
print(reversed_rows)  # Output: [[7 8 9], [4 5 6], [1 2 3]]

# Reversing columns
reversed_columns = np.flip(array2d, axis=1)
print(reversed_columns)  # Output: [[3 2 1], [6 5 4], [9 8 7]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


Reversing along multiple axes:
You can also reverse the array along multiple axes by passing a tuple of axes to the flip() function.

In [5]:
# Reversing both rows and columns
reversed_both = np.flip(array2d, axis=(0, 1))
print(reversed_both)  # Output: [[9 8 7], [6 5 4], [3 2 1]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]


Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Ans. Determining the Data Type of Elements in a NumPy Array

NumPy provides the dtype attribute to access the data type of the elements in an array. This attribute returns a NumPy data type object, which represents the type of data stored in the array.

In [7]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
data_type = array.dtype

print(data_type)

int32


In [ ]:
#In the example above, the output int32 indicates that the elements in the array are 32-bit integers.

Importance of Data Types in Memory Management and Performance

Understanding and choosing the appropriate data type for your NumPy arrays is crucial for efficient memory management and performance:

Memory Usage:

Correct data type: Using the correct data type ensures that only the necessary amount of memory is allocated for each element. For example, using int8 for small integers instead of int64 can significantly reduce memory consumption.
Avoid unnecessary conversions: Performing unnecessary data type conversions can be computationally expensive and can impact performance.
Performance:

Optimized operations: NumPy operations are often optimized for specific data types. Using the correct data type can lead to faster calculations.
Memory access patterns: The data type can influence how elements are stored in memory, which can affect memory access patterns and performance. For example, arrays with elements that are multiples of 64 bits (e.g., int64, float64) can benefit from efficient memory access.
Best Practices:

Use the appropriate data type: Choose the data type that best represents the range and precision of your data.
Avoid unnecessary conversions: Try to perform operations directly on arrays with compatible data types to minimize conversions.

Be aware of memory limitations: Consider the memory requirements of your arrays, especially when working with large datasets.


Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans. NumPy arrays, or ndarrays, are multi-dimensional arrays that provide efficient storage and manipulation of numerical data in Python. They are the fundamental data structure in NumPy and offer several advantages over standard Python lists.

Key Features of ndarrays:

Homogeneous Data Type: All elements in an ndarray must be of the same data type (e.g., int, float, bool).
Fixed Size: The size of an ndarray cannot be changed after creation.
Efficient Operations: NumPy provides optimized functions for various mathematical operations, making it much faster than using Python lists for numerical computations.

Broadcasting: NumPy supports broadcasting, which allows for element-wise operations between arrays of different shapes.
Indexing and Slicing: ndarrays can be indexed and sliced to access or modify specific elements or subsets of the array.

Vectorization: Many operations in NumPy can be vectorized, meaning they can be performed on entire arrays at once, leading to significant performance improvements.

Shape and Dimensions: ndarrays have a shape attribute that specifies the number of elements along each axis.

Differences from Standard Python Lists:

Data Type Homogeneity: Python lists can store elements of different data types, while ndarrays require all elements to be of the same type.
Fixed Size: Python lists are dynamic and can change size during runtime, while ndarrays have a fixed size.

Performance: NumPy ndarrays are optimized for numerical operations and are generally much faster than Python lists, especially for large datasets.
Vectorization: Python lists do not support vectorization, making them less efficient for numerical computations.

Indexing and Slicing: While both ndarrays and lists support indexing and slicing, ndarrays often have more flexible indexing options.
Shape and Dimensions: ndarrays have a well-defined shape and can be multi-dimensional, while Python lists are essentially one-dimensional.

In summary, ndarrays in NumPy offer a powerful and efficient way to work with numerical data in Python. Their homogeneity, fixed size, optimized operations, and other features make them a valuable tool for scientific computing, data analysis, and machine learning.


Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans. NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to the following factors:
Vectorization:
•	NumPy operations are designed to be vectorized, meaning they can operate on entire arrays at once, avoiding costly element-wise loops. This leads to dramatic performance improvements, especially for large datasets.
Memory Efficiency:
•	NumPy arrays are stored in contiguous memory blocks, which allows for efficient memory access. This is in contrast to Python lists, which can have scattered memory allocations, leading to slower access times.
•	NumPy arrays also have a fixed size, which can help to avoid unnecessary memory reallocations that can occur with Python lists.
Optimized Algorithms:
•	NumPy is built on highly optimized C and Fortran libraries, which provide efficient implementations of many mathematical operations. This means that NumPy functions are often significantly faster than their Python equivalents.
Data Type Homogeneity:
•	NumPy arrays require all elements to be of the same data type, which allows for more efficient memory usage and optimized operations. Python lists, on the other hand, can store elements of different data types, which can lead to overhead and slower performance.
Examples of Performance Gains:
•	Matrix Multiplication: NumPy's dot function for matrix multiplication is significantly faster than using nested loops in Python.
•	Element-wise Operations: Arithmetic operations like addition, subtraction, multiplication, and division can be performed on entire NumPy arrays at once, leading to substantial speedups.
•	Trigonometric Functions: NumPy provides optimized implementations of trigonometric functions, which can be significantly faster than using Python's built-in functions.
In conclusion, NumPy arrays offer substantial performance advantages over Python lists for large-scale numerical operations due to their vectorization, memory efficiency, optimized algorithms, and data type homogeneity. By using NumPy, you can significantly improve the speed and efficiency of your numerical computations.


Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output

Ans. vstack() and hstack() are two functions in NumPy used to vertically and horizontally stack arrays, respectively.

vstack()

- Stacks arrays vertically, meaning it appends the arrays one below the other.
- The arrays must have the same number of columns.

In [8]:
import numpy as np

array1 = np.array([[1, 2],
                  [3, 4]])

array2 = np.array([[5, 6],
                  [7, 8]])

stacked_array = np.vstack((array1, array2))

print(stacked_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


hstack()

- Stacks arrays horizontally, meaning it appends the arrays side by side.
- The arrays must have the same number of rows.

In [9]:
array1 = np.array([[1, 2],
                  [3, 4]])

array2 = np.array([[5, 6],
                  [7, 8]])

stacked_array = np.hstack((array1, array2))

print(stacked_array)

[[1 2 5 6]
 [3 4 7 8]]


Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans. fliplr() and flipud() are two functions in NumPy used to flip arrays along specific axes:

fliplr()

Flips an array along the left-right axis (axis 1).
This means that the columns of the array are reversed.

In [10]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6]])

flipped_array = np.fliplr(array)

print(flipped_array)

[[3 2 1]
 [6 5 4]]


flipud()

Flips an array along the up-down axis (axis 0).
This means that the rows of the array are reversed.

In [11]:
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

flipped_array = np.flipud(array)

print(flipped_array)

[[4 5 6]
 [1 2 3]]


Effects on Various Array Dimensions:

1D arrays: Both fliplr() and flipud() have the same effect on 1D arrays, which is to reverse the order of elements.
2D arrays: fliplr() reverses the columns, while flipud() reverses the rows.
3D arrays: fliplr() reverses the elements along the second axis (columns), and flipud() reverses the elements along the first axis (rows).

In summary, fliplr() and flipud() provide convenient ways to reverse the elements of an array along specific axes, which can be useful for various data manipulation tasks.

Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans. array_split() in NumPy is a function used to split an array into a specified number of sub-arrays. It is a versatile tool for dividing data into smaller, manageable chunks.
Functionality:
•	Takes an array and an integer sections as input.
•	Splits the array into sections sub-arrays.
•	The sub-arrays are approximately equal in size.
•	If the array cannot be evenly divided, the last sub-array will be smaller than the others.
Uneven Splits:
•	When the array cannot be evenly divided, array_split() ensures that the sub-arrays are as evenly distributed as possible.
•	The last sub-array will contain the remaining elements.



In [12]:
import numpy as np

array = np.arange(10)

# Split into 3 sub-arrays
sub_arrays1 = np.array_split(array, 3)

print(sub_arrays1)

# Split into 4 sub-arrays
sub_arrays2 = np.array_split(array, 4)

print(sub_arrays2)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]


Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans. In NumPy, two important concepts that significantly enhance the performance of array operations are vectorization and broadcasting. These concepts allow for more efficient computation by avoiding the need for explicit loops and enabling operations on arrays of different shapes.

1. Vectorization:
Vectorization refers to the process of applying operations on entire arrays (or large chunks of data) at once, rather than processing individual elements via loops. This is possible because NumPy internally uses optimized, low-level C code to handle array operations, making these operations much faster than if they were implemented using Python loops.

For example, consider two arrays a and b, each containing 1 million elements. To add them element-wise, you can simply use:


In [13]:

result = a + b  # Vectorized operation

#Without vectorization, you would need a loop like:
result = [a[i] + b[i] for i in range(len(a))]


Vectorized operations are not only more concise and readable but also significantly faster because they leverage hardware optimizations like SIMD (Single Instruction, Multiple Data).

2. Broadcasting:
Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes. It "stretches" the smaller array along the dimensions where it has size 1 so that it matches the shape of the larger array, enabling element-wise operations without making copies of data.

For example, suppose you want to add a scalar to each element of a 2D array:

In [14]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
result = array_2d + scalar  # Broadcasting

#Here, scalar is treated as a 2x3 array where each element is 10, and the addition is performed element-wise.

Benefits of Vectorization and Broadcasting:
Performance: Both vectorization and broadcasting lead to faster execution as they minimize explicit loops and take advantage of low-level optimizations.
Memory efficiency: Broadcasting allows NumPy to perform operations without creating large intermediate arrays, saving memory and speeding up computation.
Concise code: Operations can be written in a single line, making the code easier to read and maintain.
In summary, vectorization and broadcasting are key features in NumPy that contribute to highly efficient array operations by reducing loops, enabling fast execution, and simplifying the code structure.

In [ ]:
'Practical Questions:'

In [ ]:
#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [15]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, (3, 3))

# Print the original array
print("Original array:")
print(array)

# Interchange rows and columns using array transposition
interchanged_array = array.T

# Print the interchanged array
print("Interchanged array:")
print(interchanged_array)

Original array:
[[ 5 94 15]
 [78 77 92]
 [84 53 43]]
Interchanged array:
[[ 5 78 84]
 [94 77 53]
 [15 92 43]]


In [ ]:
#Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [16]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array.reshape(5, 2)

print("Original array:", array)
print("Reshaped 2x5 array:", array_2x5)
print("Reshaped 5x2 array:", array_5x2)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reshaped 2x5 array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped 5x2 array: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [17]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array = np.random.rand(4, 4)

# Add a border of zeros around it
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print("Original array:")
print(array)

print("Array with border:")
print(array_with_border)

Original array:
[[0.95175892 0.99592134 0.70903086 0.33610246]
 [0.3729434  0.33249515 0.05354474 0.94956831]
 [0.05597447 0.07037718 0.17393438 0.98432928]
 [0.1457811  0.3665205  0.9401686  0.98871286]]
Array with border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.95175892 0.99592134 0.70903086 0.33610246 0.        ]
 [0.         0.3729434  0.33249515 0.05354474 0.94956831 0.        ]
 [0.         0.05597447 0.07037718 0.17393438 0.98432928 0.        ]
 [0.         0.1457811  0.3665205  0.9401686  0.98871286 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [18]:
import numpy as np

array = np.arange(10, 61, 5)

print(array)

[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [20]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply uppercase transformation
upper_case = np.char.upper(arr)

# Apply lowercase transformation
lower_case = np.char.lower(arr)

# Apply title case transformation
title_case = np.char.title(arr)

# Print the results
print("Original Array:", arr)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [ ]:
#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [21]:
import numpy as np

# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', arr)

# Print the result
print("Original Array:", arr)
print("Array with spaces between characters:", spaced_words)


Original Array: ['python' 'numpy' 'pandas']
Array with spaces between characters: ['p y t h o n' 'n u m p y' 'p a n d a s']


In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [22]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = np.add(array1, array2)

# Perform element-wise subtraction
subtraction = np.subtract(array1, array2)

# Perform element-wise multiplication
multiplication = np.multiply(array1, array2)

# Perform element-wise division
division = np.divide(array1, array2)

# Print the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nElement-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [23]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [24]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Print the results
print("Random Array:", random_array)
print("\nPrime Numbers in the Array:", prime_numbers)


Random Array: [ 983  809  129  457  867  219  948  589  764  612  139  513  220  951
  935  682  166  392  443  338    3  550  666  417  417   66  881  389
  302  868  551  293  452  140  214  628  666  372  359  374  458  955
  341  358  980  526  225  864  392  383  200  164  739  235   36  637
  302  938  602  392   47  989  167  309  403  331  772  793  953  618
  936   64  452  947  843  958  264  283  486  850  208  896  424  478
  336  232  966  168  727  336  704  126  993  328  813  381  824 1000
  615  634]

Prime Numbers in the Array: [983, 809, 457, 139, 443, 3, 881, 389, 293, 359, 383, 739, 47, 167, 331, 953, 947, 283, 727]


In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [26]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month
daily_temperatures = np.random.randint(60, 90, 30)

# Calculate weekly averages using array_split
weekly_averages = np.array_split(daily_temperatures, 4)
weekly_averages = [np.mean(week) for week in weekly_averages]

# Display the weekly averages
print("Weekly Averages:")
for week, average in enumerate(weekly_averages, 1):
    print(f"Week {week}: {average:.2f}")

Weekly Averages:
Week 1: 72.62
Week 2: 74.38
Week 3: 72.29
Week 4: 69.00
